# Server-Sent Events 기반 MCP 서버 설정
# HTTPS 및 포트 설정
server:
  port: 48088
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
  tomcat:
    max-swallow-size: 2MB
    max-http-form-post-size: 2MB
spring:
  application:
    name: sse-mcp-server-demo
    description: "SSE 기반 MCP 서버 데모 애플리케이션"
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: sse-mcp-server-demo
        version: 0.0.1
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp/message
        type: sync
        capabilities:
          tool: true
          completion: true
          resource: true
          prompt: true

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
